Make things work

diff --git a/camanage b/camanage
--- a/camanage
+++ b/camanage
@@ -14,6 +14,11 @@ then
 	. /var/lib/eid/config
 fi
 
+if [ ! -d /var/lib/eid/crls ]
+then
+	mkdir /var/lib/eid/crls
+fi
+
 export EID_TEST_CA_TYPE="${EID_TEST_CA_TYPE:-sha256}"
 export EID_TEST_CA_ORG="${EID_TEST_CA_ORG:-Acme, Inc}"
 export EID_TEST_CA_OCSP="${EID_TEST_CA_OCSP:-http://localhost/ocsp}"
@@ -28,23 +33,25 @@ case "$EID_TEST_CA_TYPE" in
 		ca_years=12
 		cert_years=10
 		key_size=2048
-		hash_alg=256
+		hash_alg=sha256
 	;;
 	sha1)
 		root_years=15
 		ca_years=12
 		cert_years=10
 		key_size=2048
-		hash_alg=1
+		hash_alg=sha1
 	;;
 	old)
 		root_years=14
 		ca_years=7
 		cert_years=5
 		key_size=1024
-		hash_alg=1
+		hash_alg=sha1
 	;;
 esac
+
+export hash_alg
 
 ca_size=$(( $key_size * 2 ))
 
@@ -83,6 +90,9 @@ usage() {
 	echo "       default."
 	echo "   revoke [<ca_name>]: revoke a certificate."
 	echo ""
+	echo " General commands:"
+	echo "  updatecrls: rebuild all CRLs (for both intermediate and root CA)"
+	echo ""
 	echo " The following environment variables are checked when the buildroot or genca"
 	echo " commands are being run:"
 	echo "  EID_TEST_CA_TYPE: The type of certificate chain that should be built."
@@ -106,20 +116,32 @@ case "$1" in
 	buildroot)
 		export EID_TEST_ROOT_NAME=${EID_TEST_ROOT_NAME:-root}
 		cd /var/lib/eid
+		if [ -f ${EID_TEST_ROOT_NAME}.key ]
+		then
+			echo "E: cannot generate root certificate: it already exists!"
+			exit 1
+		fi
 		days=$(( ( $(date -d "now + $root_years years" +%s) - $(date -d now +%s) ) / 86400 ))
-		openssl req -batch -days $days -nodes -new -newkey rsa:$ca_size -x509 -sha$hash_alg -config /usr/share/eid-test/root/root.conf -keyout ${EID_TEST_ROOT_NAME}.key -out ${EID_TEST_ROOT_NAME}.crt
+		openssl req -batch -days $days -nodes -new -newkey rsa:$ca_size -x509 -$hash_alg -config /usr/share/eid-test/root/root.conf -keyout ${EID_TEST_ROOT_NAME}.key -out ${EID_TEST_ROOT_NAME}.crt
 		touch /var/lib/eid/${EID_TEST_ROOT_NAME}-index.txt
 		echo "01" > /var/lib/eid/${EID_TEST_ROOT_NAME}-serial
-		openssl ca -batch -config /usr/share/eid-test/root/root.conf -gencrl -out /var/lib/eid/crls/${EID_TEST_ROOT_NAME}.crl
+		openssl ca -batch -config /usr/share/eid-test/root/root.conf -gencrl -crldays 30 -out crls/${EID_TEST_ROOT_NAME}.crl
 		echo "Root CA \"$EID_TEST_ROOT_NAME\" created. Now generate the intermediate CA with the \"genca\" command."
 		writeconf=1
 	;;
 	genca)
+		export EID_TEST_ROOT_NAME=${EID_TEST_ROOT_NAME:-root}
 		export EID_TEST_CA_NAME="${EID_TEST_CA_NAME:-ca}"
 		cd /var/lib/eid
+		if [ -f ${EID_TEST_CA_NAME}.key ]
+		then
+			echo "E: cannot generate CA certificate: it already exists!"
+			exit 1
+		fi
 		EID_TEST_CA_NAME=$(echo -n "$EID_TEST_CA_NAME" | sed -e 's/[^[a-zA-Z0-9]]/_/g')
 		openssl req -batch -nodes -new -newkey rsa:$ca_size -keyout ${EID_TEST_CA_NAME}.key -out ${EID_TEST_CA_NAME}.csr -config /usr/share/eid-test/intermediate/ca.conf
-		openssl ca -batch -config /usr/share/eid-test/intermediate/ca.conf -gencrl -out /var/lib/eid/crls/${EID_TEST_CA_NAME}.crl
+		touch /var/lib/eid/${EID_TEST_CA_NAME}-index.txt
+		echo "01" > /var/lib/eid/${EID_TEST_CA_NAME}-serial
 		echo "Intermediate CA \"$EID_TEST_CA_NAME\" generated."
 		writeconf=1
 	;;
@@ -134,7 +156,8 @@ case "$1" in
 	buildca)
 		shift
 		$0 genca "$@"
-		exec $0 signca "$@"
+		$0 signca "$@"
+		exec $0 updatecrls
 	;;
 	run)
 		if [ ! -f "/var/lib/eid/${EID_TEST_ROOT_NAME}.key" ]
@@ -142,8 +165,15 @@ case "$1" in
 			exec $0 "not initialized"
 			exit 1
 		fi
-		systemctl start apache2
-		sleep
+		service apache2 start
+		service cron start
+		while true
+		do
+			# We don't want this to ever stop, but we do
+			# want to use the init scripts etc. So just loop
+			# around a sleep call for a very long time...
+			sleep 86400
+		done
 	;;
 	ocspsigner)
 		notyet
@@ -153,6 +183,11 @@ case "$1" in
 	;;
 	importsigner)
 		notyet
+	;;
+	updatecrls)
+		cd /var/lib/eid
+		openssl ca -batch -config /usr/share/eid-test/root/root.conf -gencrl -crldays 30 -out crls/${EID_TEST_ROOT_NAME}.crl
+		openssl ca -batch -config /usr/share/eid-test/intermediate/ca.conf -gencrl -crldays 7 -out crls/${EID_TEST_CA_NAME}.crl
 	;;
 	exportcrl)
 		notyet
